"""
FinTelemetry FastAPI Backend — Gold Layer API
==============================================
Exposes the audit_warehouse.db (DuckDB) via a REST API on port 8000.

Mode switching
--------------
Set the PIPELINE_MODE environment variable before starting the server:

    PIPELINE_MODE=mock   (default)
        Serves data directly from the in-memory mock dataset generated by
        core_pipelines/mock_data.py.  No database required — ideal for
        front-end development and CI.

    PIPELINE_MODE=live
        Reads from the Gold DuckDB populated by the live_ingestion pipeline.
        Requires the Silver pipeline to have run at least once:
            python -m backend.live_ingestion.pyspark_processor

Running the server
------------------
    # from the project root:
    uvicorn backend.api.main:app --port 8000 --reload

    # or run this file directly:
    python -m backend.api.main
"""

import hashlib
import math
import os
import random
import sys
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Path setup — allow imports from project root
# ---------------------------------------------------------------------------

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from fastapi import BackgroundTasks, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from backend.core_pipelines.db_client import DBConfig, fetch_audit_records, get_connection, initialize_schema
from backend.core_pipelines.mock_data import get_mock_sec_filings

# ---------------------------------------------------------------------------
# Runtime configuration
# ---------------------------------------------------------------------------

PIPELINE_MODE = os.getenv("PIPELINE_MODE", "mock").lower()
GOLD_DB_PATH  = Path(os.getenv("GOLD_DB_PATH", "backend/data_store/audit_warehouse.db"))

# ---------------------------------------------------------------------------
# Filing record shaping
# ---------------------------------------------------------------------------

_MOCK_ASSIGNEES = [
    "Sarah M.", "James K.", "Emily R.", "David L.",
    "Karen T.", "Michael B.", "Alice C.", "Thomas W.",
]


def _parse_age_token(id_str: str, score: float) -> Optional[str]:
    """Generate a deterministic alert age from id + anomaly score."""
    try:
        id_num = int(hashlib.md5(id_str.encode()).hexdigest(), 16) % 1000
    except Exception:
        id_num = 1
    age_hours = max(1, (id_num * 11 + int(score * 137)) % 193)
    return f"{age_hours}h" if age_hours < 24 else f"{age_hours // 24}d"


def _to_filing_record(row: dict) -> dict:
    """
    Shapes a raw audit_triage row (from DB or mock) into the API response
    object consumed by the React dashboard.  Mirrors the logic in
    frontend/dev_server.js :: toFilingRecord().
    """
    score     = float(row.get("ml_anomaly_score") or 0)
    known_vio = bool(row.get("known_rule_violation"))
    ml_flag   = bool(row.get("ml_anomaly_flag"))
    is_triage = known_vio or ml_flag

    # Cluster classification
    isolation_cluster = (
        "Cluster-7 (High-Risk)"   if score >= 0.8 else
        "Cluster-3 (Medium-Risk)" if score >= 0.5 else
        "Cluster-2 (Low-Risk)"
    )

    # 95% confidence interval
    ci_low  = round(max(0.0, score - 0.04), 2)
    ci_high = round(min(1.0, score + 0.04), 2)

    issue_type = (
        "Rule Violation" if known_vio else
        "ML Anomaly"     if ml_flag   else
        "None"
    )
    severity = (
        "violation" if known_vio else
        "anomaly"   if ml_flag   else
        "healthy"
    )
    status = (
        "Needs Review" if known_vio else
        "In Progress"  if ml_flag   else
        "Resolved"
    )

    id_str = str(row.get("id", "1"))
    try:
        id_num = int(id_str.split("-")[0]) if "-" in id_str else int(id_str)
    except (ValueError, IndexError):
        id_num = abs(hash(id_str)) % 10000

    assignee  = _MOCK_ASSIGNEES[id_num % len(_MOCK_ASSIGNEES)] if is_triage else None
    alert_age = _parse_age_token(id_str, score) if is_triage else None

    raw_ocf = row.get("operating_cash_flow")
    ocf_float = float(raw_ocf) if raw_ocf is not None else 0.0
    revenue_str = f"${ocf_float / 1e9:.1f}B" if raw_ocf is not None else None

    rev_growth  = float(row.get("revenue_growth") or 0)
    cash_ratio  = round(ocf_float / 1e10, 3) if ocf_float != 0 else 0.0

    filing_date = row.get("filing_date")
    if filing_date and hasattr(filing_date, "isoformat"):
        filing_date = filing_date.isoformat()[:10]
    elif filing_date:
        filing_date = str(filing_date)[:10]
    else:
        filing_date = "N/A"

    created_at = row.get("created_at")
    if created_at and hasattr(created_at, "isoformat"):
        ingestion_ts = created_at.isoformat()
    else:
        ingestion_ts = datetime.now(timezone.utc).isoformat()

    return {
        "id":                id_str,
        "company":           str(row.get("company_name", "")),
        "filingDate":        filing_date,
        "issueType":         issue_type,
        "severity":          severity,
        "cik":               str(row.get("cik") or "N/A"),
        "formType":          str(row.get("form_type") or "N/A"),
        "revenue":           revenue_str,
        "knownRuleViolation":known_vio,
        "mlAnomalyFlag":     ml_flag,
        "needsTriage":       is_triage,
        "status":            status,
        "assignee":          assignee,
        "alertAge":          alert_age,
        "violationDetails":  row.get("root_cause_message"),
        "mlTelemetry": {
            "anomalyScore":       score,
            "isolationCluster":   isolation_cluster,
            "ingestionTs":        ingestion_ts,
            "modelVersion":       "IsoForest-v2.4",
            "featureContrib": {
                "revenueGrowthDelta": round(rev_growth, 3),
                "cashFlowRatio":      cash_ratio,
                "filingFrequency":    round(score * 0.3, 3),
            },
            "confidenceInterval": f"{ci_low:.2f} – {ci_high:.2f}",
        },
    }


# ---------------------------------------------------------------------------
# Data sources
# ---------------------------------------------------------------------------

def _get_mock_filings() -> list[dict]:
    """Returns shaped records from the in-memory mock dataset."""
    raw_rows = get_mock_sec_filings()
    result   = []
    for i, f in enumerate(raw_rows, 1):
        filing_date = f.get("filing_date")
        if hasattr(filing_date, "isoformat"):
            filing_date = filing_date.isoformat()

        row = {
            "id":                   str(i),
            "company_name":         f["company_name"],
            "filing_date":          filing_date,
            "cik":                  f.get("cik"),
            "form_type":            f.get("form_type"),
            "revenue_growth":       None,
            "operating_cash_flow":  float(f["revenue_usd"]) if f.get("revenue_usd") else None,
            "known_rule_violation": f["known_rule_violation"],
            "ml_anomaly_flag":      f["ml_anomaly_flag"],
            "ml_anomaly_score":     f["ml_anomaly_score"],
            "root_cause_message":   f.get("root_cause_message"),
            "created_at":           None,
        }
        result.append(_to_filing_record(row))
    return result


def _get_live_filings(limit: int = 200) -> list[dict]:
    """Queries the Gold DuckDB and returns shaped filing records."""
    db_cfg = DBConfig(db_path=GOLD_DB_PATH, read_only=True)
    try:
        with get_connection(db_cfg) as conn:
            df = fetch_audit_records(conn, limit=limit)
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"DuckDB unavailable: {exc}") from exc

    return [_to_filing_record(row) for row in df.to_dict("records")]


def _get_filings(limit: int = 200) -> list[dict]:
    return _get_mock_filings() if PIPELINE_MODE == "mock" else _get_live_filings(limit)


# ---------------------------------------------------------------------------
# Pipeline trigger (live mode only)
# ---------------------------------------------------------------------------

def _trigger_live_ingestion() -> dict:
    """
    Runs the full Bronze → Silver → Gold pipeline in a background thread.
    Returns immediately; check /api/health for pipeline status.
    """
    try:
        from backend.live_ingestion.azure_blob_stream import BronzeIngestionConfig, ingest_bronze
        from backend.live_ingestion.pyspark_processor import SilverProcessorConfig, run_silver_pipeline

        bronze_cfg = BronzeIngestionConfig()
        silver_cfg = SilverProcessorConfig(db_path=GOLD_DB_PATH)
        bronze_df  = ingest_bronze(bronze_cfg)
        run_silver_pipeline(bronze_df, silver_cfg)
        return {"status": "completed"}
    except Exception as exc:
        return {"status": "error", "detail": str(exc)}


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    if PIPELINE_MODE == "live":
        # Ensure schema exists on startup so first GET /api/filings doesn't fail
        try:
            db_cfg = DBConfig(db_path=GOLD_DB_PATH)
            with get_connection(db_cfg) as conn:
                initialize_schema(conn)
        except Exception as exc:
            import logging
            logging.getLogger(__name__).warning("Could not pre-init schema: %s", exc)
    yield


app = FastAPI(
    title="FinTelemetry Compliance API",
    version="2.0.0",
    description=(
        "Gold layer REST API for the SEC EDGAR compliance dashboard. "
        "Switch data source via PIPELINE_MODE=mock|live."
    ),
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/api/health")
def health_check() -> dict:
    """Returns server status and active pipeline mode."""
    return {
        "status":        "ok",
        "pipeline_mode": PIPELINE_MODE,
        "db_path":       str(GOLD_DB_PATH) if PIPELINE_MODE == "live" else None,
        "timestamp":     datetime.now(timezone.utc).isoformat(),
    }


@app.get("/api/filings")
def list_filings(limit: int = Query(default=200, ge=1, le=1000)) -> list[dict]:
    """
    Returns a list of shaped filing records.

    In mock mode, limit is applied after generating all 50 mock records.
    In live mode, limit is passed to the DuckDB query.
    """
    return _get_filings(limit)[:limit]


@app.get("/api/filings/{filing_id}")
def get_filing(filing_id: str) -> dict:
    """Returns a single filing record by its id."""
    records = _get_filings()
    match   = next((r for r in records if r["id"] == filing_id), None)
    if not match:
        raise HTTPException(status_code=404, detail=f"Filing '{filing_id}' not found.")
    return match


@app.get("/api/filings/stats/summary")
def filing_stats() -> dict:
    """Aggregate counts for the summary stat cards in the dashboard."""
    records    = _get_filings()
    violations = sum(1 for r in records if r["knownRuleViolation"])
    anomalies  = sum(1 for r in records if r["mlAnomalyFlag"])
    return {
        "total":      len(records),
        "violations": violations,
        "anomalies":  anomalies,
        "healthy":    len(records) - violations - anomalies,
        "mode":       PIPELINE_MODE,
    }


@app.get("/api/pii-audit")
def get_pii_audit_log(limit: int = Query(default=200, ge=1, le=2000)) -> list[dict]:
    """
    Returns PII detection audit log entries from pii_audit_log.

    Each entry records which field, which PII type, how many rows were affected,
    and which pipeline run produced the detection.  Raw PII values are never stored.

    Returns an empty list in mock mode until ingestion_pipeline.py has been run
    at least once (which populates both audit_triage and pii_audit_log).
    """
    db_cfg = DBConfig(db_path=GOLD_DB_PATH, read_only=True)
    try:
        with get_connection(db_cfg) as conn:
            df = conn.execute(
                "SELECT * FROM pii_audit_log ORDER BY detection_ts DESC LIMIT ?",
                [limit],
            ).df()
        return df.to_dict("records")
    except Exception as exc:
        # pii_audit_log doesn't exist yet (no ingestion has run), or DB is
        # unavailable — return empty list rather than a 503 so the dashboard
        # renders cleanly before first pipeline execution.
        if "pii_audit_log" in str(exc) or "does not exist" in str(exc).lower():
            return []
        raise HTTPException(
            status_code=503,
            detail=f"pii_audit_log unavailable: {exc}",
        ) from exc


@app.post("/api/pipeline/run")
def trigger_pipeline(background_tasks: BackgroundTasks) -> dict:
    """
    Triggers a full Bronze → Silver → Gold ingestion run (live mode only).
    The job runs in a background thread; the endpoint returns immediately.
    """
    if PIPELINE_MODE != "live":
        raise HTTPException(
            status_code=400,
            detail="Pipeline trigger is only available in PIPELINE_MODE=live.",
        )
    background_tasks.add_task(_trigger_live_ingestion)
    return {"status": "accepted", "message": "Pipeline triggered. Check /api/health for progress."}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    port = int(os.getenv("API_PORT", "8000"))
    print(f"\n FinTelemetry API starting on http://localhost:{port}")
    print(f" PIPELINE_MODE = {PIPELINE_MODE}")
    if PIPELINE_MODE == "live":
        print(f" GOLD_DB_PATH  = {GOLD_DB_PATH}")
    print(" Press Ctrl+C to stop.\n")

    uvicorn.run(
        "backend.api.main:app",
        host="0.0.0.0",
        port=port,
        reload=True,
        reload_dirs=[str(_PROJECT_ROOT / "backend")],
    )
